site_name: CNC-CMD知识共享平台
site_url: https://cnc-cmd.github.io/GCR/
repo_url: https://github.com/cnc-cmd/GCR.git

theme:
  name: material
  language: zh
  features:
        - navigation.tabs
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.top
        - search.suggest
        - search.highlight
        - search.share  
        - content.code.copy
        - content.code.select
        - content.code.annotate
        - toc.follow

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cnc-cmd/GCR
      name: CND-CMD知识共享平台

plugins:
  - search
  - tags

nav:
  - 主页: 'index.md'

  - 学习资源: 
    - 综合网站: '学习资源/综合网站.md'
    - 计算机基础:
      - 计算机课程综合: '学习资源/计算机基础/计算机课程综合.md'
      - 计算机组成原理: '学习资源/计算机基础/计算机组成原理.md'
      - 操作系统: '学习资源/计算机基础/操作系统.md'
      - 计算机网络: '学习资源/计算机基础/计算机网络.md'
      - 数据结构: '学习资源/计算机基础/数据结构与算法.md'
    - 编程语言:
      - C语言: '学习资源/编程语言/C语言.md'
      - C++: '学习资源/编程语言/C++.md'
      - Java: '学习资源/编程语言/Java.md'
      - JavaScript: '学习资源/编程语言/JavaScript.md'
      - Python: '学习资源/编程语言/Python.md'
      - Golang: '学习资源/编程语言/Golang.md'
      - Rust: '学习资源/编程语言/Rust.md'
    - 实用工具:
      - git: '学习资源/实用工具/git.md'
      - vscode插件: '学习资源/实用工具/vscode插件.md'
    - 前端:
      - 前端通识: '学习资源/前端/前端通识.md'
      - HTML/CSS: '学习资源/前端/HTMLCSS.md'
      - JavaScript: '学习资源/前端/JavaScript.md'
      - Vue: '学习资源/前端/Vue.md'
    - 后端: 
      - 后端通识: '学习资源/后端/后端通识.md'
      - Java后端: '学习资源/后端/Java后端.md'
      - Go后端: '学习资源/后端/Go后端.md'
    - 技术文章:
      - 文章合辑: '学习资源/技术文章/ArticleCollection.md'
  - 学习路线: 'LearningPath'
  - 友链: 'friend.md'
  - 关于: 'about.md'