site_name: CNC-CMD知识共享平台
site_url: https://cnc-cmd.github.io/GCR/
repo_url: https://github.com/cnc-cmd/GCR.git

theme:
  name: material
  language: zh
  features:
        - navigation.tabs
        - navigation.instant
        - navigation.instant.prefetch
        - navigation.instant.progress
        - navigation.sections
        - navigation.top
        - search.suggest
        - search.highlight
        - search.share  
        - content.code.copy
        - content.code.select
        - content.code.annotate
        

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cnc-cmd/GCR
      name: CND-CMD知识共享平台

plugins:
  - search
  - tags

nav:
  - 主页: 'index.md'
  - 技术文章:
    - 文章合辑: '技术文章/ArticleCollection.md'
    - 实用工具:
      - git: '实用工具/git.md'
      - vscode插件: '实用工具/vscode.md'
  - 学习资源: 
    - 综合: '学习资源/gcr.md'
    - 后端: '学习资源/backend.md'
  - 项目推荐: 'project.md'
  - 学习路线: 'LearnPath.md'
  - 友链: 'friend.md'
  - 关于: 'about.md'