name: ci

on:
  push: # push è§¦å‘
    paths-ignore: # å¿½ç•¥READMEçš„æ›´æ”¹ï¼Œé¿å…pushåè§¦å‘workflow
      - 'README.md'
    branches: # pushåˆ°mainæˆ–masteråˆ†æ”¯æ—¶è§¦å‘
      - master
      - main
  pull_request: # PR è§¦å‘
    paths-ignore:
      - 'README.md'
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-test: # æ„å»ºå’Œæµ‹è¯•
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: è®¾ç½® Python3 ç¯å¢ƒ
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: ğŸ“– å®‰è£…ä¾èµ– && å®‰è£…Mkdocsæ’ä»¶
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-glightbox

      - name: ğŸš€ æ„å»º MKDOCS
        run: mkdocs build

  deploy: # éƒ¨ç½²
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: è®¾ç½® Git èº«ä»½
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: å®‰è£… Python3 ç¯å¢ƒ
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: ğŸ“– å®‰è£…ä¾èµ–
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-glightbox

      - name: ğŸš€ éƒ¨ç½²MKDOCS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
